<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Seeder;

class PageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('pages')->insert([
            [
                'title' => 'WELCOME',
                'slug' => 'welcome',
                'image' => null,
                'content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'INDEX BOTTOM',
                'slug' => 'index-bottom',
                'image' => null,
                'content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'ABOUT US PAGE',
                'slug' => 'about-us-page',
                'image' => null,
                'content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'CLASS SIDE BAR',
                'slug' => 'class-side-bar',
                'image' => null,
                'content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'VISION&MISSION',
                'slug' => 'vision&mission',
                'image' => null,
                'content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'CONTACT US',
                'slug' => 'contact-us',
                'image' => null,
                'content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'FAQ SING UP AND SIGN IN',
                'slug' => 'faq-sing-up-and-sign-in',
                'image' => null,
                'content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'FAQ  KYC APPROVAL',
                'slug' => 'faq-kyc-approval',
                'image' => null,
                'content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'FAQ  BUY PACKAGES',
                'slug' => 'faq-buy-packages',
                'image' => null,
                'content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'FAQ  INVITE MEMBERS',
                'slug' => 'faq-invite-members',
                'image' => null,
                'content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'FAQ WITHDRAW MONEY',
                'slug' => 'faq-withdraw-money',
                'image' => null,
                'content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'HOW TO IT WORKS',
                'slug' => 'how-to-it-works',
                'image' => null,
                'content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'How do I change my password?',
                'parent_id ' => 7,
                'slug' => 'how-do-i-change-my-password',
                'image' => null,
                'content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'How do I sign up?',
                'parent_id ' => 7,
                'slug' => 'how-do-i-sign-up',
                'image' => null,
                'content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Can I remove a post?',
                'parent_id ' => 7,
                'slug' => 'can-i-remove-a-post',
                'image' => null,
                'content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'How do reviews work?',
                'parent_id ' => 7,
                'slug' => 'how-do-reviews-work',
                'image' => null,
                'content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Kyc Approval  Question 01 ?',
                'parent_id ' => 8,
                'slug' => 'kyc-approval-question-01',
                'image' => null,
                'content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Kyc Approval  Question 02 ?',
                'parent_id ' => 8,
                'slug' => 'kyc-approval-question-02',
                'image' => null,
                'content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Kyc Approval  Question 03 ?',
                'parent_id ' => 8,
                'slug' => 'kyc-approval-question-03',
                'image' => null,
                'content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Kyc Approval  Question 04 ?',
                'parent_id ' => 8,
                'slug' => 'kyc-approval-question-04',
                'image' => null,
                'content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Faq Buy Packages  Question 01 ?',
                'parent_id ' => 9,
                'slug' => 'faq-buy-packages-question-01',
                'image' => null,
                'content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Faq Buy Packages  Question 02 ?',
                'parent_id ' => 9,
                'slug' => 'faq-buy-packages-question-02',
                'image' => null,
                'content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Faq Buy Packages  Question 03 ?',
                'parent_id ' => 9,
                'slug' => 'faq-buy-packages-question-03',
                'image' => null,
                'content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Faq Buy Packages  Question 04 ?',
                'parent_id ' => 9,
                'slug' => 'faq-buy-packages-question-04',
                'image' => null,
                'content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Faq Invite Members Question  01 ?',
                'parent_id ' => 10,
                'slug' => 'faq-invite-members-question-01',
                'image' => null,
                'content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Faq Invite Members Question  02 ?',
                'parent_id ' => 10,
                'slug' => 'faq-invite-members-question-02',
                'image' => null,
                'content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Faq Invite Members  Question  03 ?',
                'parent_id ' => 10,
                'slug' => 'faq-invite-members-question-03',
                'image' => null,
                'content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Faq Invite Members  Question 04 ?',
                'parent_id ' => 10,
                'slug' => 'faq-invite-members-question-04',
                'image' => null,
                'content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Faq Withdraw Money Question 01 ?',
                'parent_id ' => 11,
                'slug' => 'faq-withdraw-money-question-01',
                'image' => null,
                'content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Faq Withdraw Money Question 02 ?',
                'parent_id ' => 11,
                'slug' => 'faq-withdraw-money-question-02',
                'image' => null,
                'content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Faq Withdraw Money Question 03 ?',
                'parent_id ' => 11,
                'slug' => 'faq-withdraw-money-question-03',
                'image' => null,
                'content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Faq Withdraw Money Question 04 ?',
                'parent_id ' => 11,
                'slug' => 'faq-withdraw-money-question-04',
                'image' => null,
                'content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'SING UP AND SIGN IN',
                'parent_id ' => 12,
                'slug' => 'sing-up-and-sign-in',
                'image' => null,
                'content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'KYC APPROVAL',
                'parent_id ' => 12,
                'slug' => 'kyc-approval',
                'image' => null,
                'content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'BUY PACKAGES',
                'parent_id ' => 12,
                'slug' => 'buy-packages',
                'image' => null,
                'content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'INVITE MEMBERS',
                'parent_id ' => 12,
                'slug' => 'invite-members',
                'image' => null,
                'content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'WITHDRAW MONEY',
                'parent_id ' => 12,
                'slug' => 'withdraw-money',
                'image' => null,
                'content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'How do I change my password?',
                'parent_id ' => 7,
                'slug' => 'how-do-i-change-my-password',
                'image' => null,
                'content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'How do I change my password?',
                'parent_id ' => 7,
                'slug' => 'how-do-i-change-my-password',
                'image' => null,
                'content' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],


        ]);
    }
}
